apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: rancher-monitoring-crd
  namespace: fleet-local
spec:
  takeOwnership: true
  chart: rancher-monitoring-crd
  releaseName: rancher-monitoring-crd
  version: 100.0.0+up16.6.0
  defaultNamespace: cattle-monitoring-system
  repoName: harvester-charts
  targets:
    - clusterName: local
      clusterSelector:
        matchExpressions:
          - key: provisioning.cattle.io/unmanaged-system-agent
            operator: DoesNotExist
